sudo: true
services:
  - docker

language: scala

scala:
  - 2.12.4

jdk:
  - oraclejdk9

script:
  - (cd test-server && docker build -t test-server .)
  - sbt test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
